/**
 * Engine Module Exports
 */

export { GameEngine, type EngineConfig } from './engine.js';
export { evaluateCondition, getAvailableChoices } from './conditions.js';
export { applyEffect, applyEffects, describeEffect } from './effects.js';
export {
  loadGame,
  discoverGames,
  getImagesDir,
  getSavesDir,
  resolveImagePath,
  listSaves,
  writeSave,
  loadSave,
  deleteSave,
  type GameFolder,
} from './loader.js';
export {
  createBlankCharacter,
  createDefaultCharacter,
  getCreationConfig,
  calculatePointsSpent,
  calculatePointsRemaining,
  increaseAttribute,
  decreaseAttribute,
  validateCharacter,
  finalizeCharacter,
  getIncreaseCost,
  getDecreaseCost,
  getAttributeCost,
  type CharacterCreationConfig,
  type AttributeChangeResult,
  type CharacterValidation,
} from './character.js';
export {
  validateStory,
  validateNode,
  isStoryValid,
  getStoryErrors,
  generateNodeId,
  generatePrefixedId,
  // Reference extraction helpers
  getConditionNodeRefs,
  getConditionItemRefs,
  getConditionAbilityRefs,
  getConditionTraitRefs,
  getConditionCompanionRefs,
  getConditionAttributeRefs,
  getConditionResourceRefs,
  getEffectItemRefs,
  getEffectAbilityRefs,
  getEffectTraitRefs,
  getEffectCompanionRefs,
  getEffectAttributeRefs,
  getEffectResourceRefs,
  findReachableNodes,
  type ValidationResult,
  type ValidationIssue,
  type ValidationSeverity,
  type ValidateOptions,
} from './validation.js';
export {
  createProject,
  saveStory,
  writeManifest,
  writeStoryNodes,
  writeAttributes,
  writeResources,
  writeCharacterCreation,
  writeItems,
  writeAbilities,
  writeTraits,
  writeCompanions,
  writeRegionComments,
  setProjectStatus,
  isPublished,
  isDraft,
  deleteProject,
  duplicateProject,
  type CreateProjectOptions,
  type CreateProjectResult,
} from './project.js';
// Editor operations
export {
  addNode,
  updateNode,
  deleteNode,
  duplicateNode,
  addChoice,
  updateChoice,
  removeChoice,
  reorderChoices,
  addEntity,
  updateEntity,
  removeEntity,
  renameNodeId,
  renameEntityId,
  findNodeReferences,
  findEntityReferences,
  getReachableNodes,
  updateManifest,
  setStartNode,
  addRegionComment,
  updateRegionComment,
  removeRegionComment,
  type EditorResult,
  type DuplicateNodeResult,
  type EntityType,
  type EntityTypeMap,
  type NodeReference,
  type EntityReference,
} from './editor.js';
// App mode state machine
export {
  appModeReducer,
  getInitialAppMode,
  type AppMode,
  type AppAction,
} from './appMode.js';
